config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  resources :races, only: %i[new create show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :race

  validates :choice, inclusion: { in: [true, false] }
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :menus, dependent: :destroy

  with_options presence: true do
    validates :set_price
    validates :gap_price
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  def new
    @menus = RakutenWebService::Ichiba::Item.search(keyword: 'フランス料理').first(15).sample(10)
    price = 0
    @menus.each { |menu| price += menu['itemPrice'] * 10 }
    num = [25, 30, 30, 35, 35, 40].sample
    @set_price = (price / num).round(-3)
  end

  def show; end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | GourmetChickenRace
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/races/new.html.slim
h1 Races#new
p 設定金額#{@set_price}円
= form_with(model: @form, url: races_path, local: true) do |f|
  = f.hidden_field :set_price, value: @set_price
  = f.fields_for :menus do |i|
    - @menus.each do |menu|
      = image_tag menu['mediumImageUrls'][0]
      = menu['itemName']
      = i.hidden_field :name, value: menu['itemName']
      = i.hidden_field :name, value: menu['itemPrice']
      = i.hidden_field :name, value: menu['affiliateUrl']
      = i.check_box :choice, { class: "form-check-input" }, true, false
      br
  = f.submit 'STOP!', class: "btn btn-primary"

app/views/races/show.html.slim
h1 Races#show
p Find me in app/views/races/show.html.slim

app/views/static_pages/top.html.slim
h1 test
= link_to 'フランス料理', new_race_path, class: "btn btn-primary"